### ISSUE TITLE
Compilation is failing because of std::collections::range::RangeArgument

### ISSUE THREAD

**Issue by yanns** [quickwit-oss/tantivy#322]
```
error[E0432]: unresolved import `std::collections::range`
  --> /Users/yannsimon/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.5.2/src/query/range_query.rs:11:23
   |
11 | use std::collections::range::RangeArgument;
   |                       ^^^^^ Could not find `range` in `collections`
```

**Comment by fulmicoton** [comment]
It sounds like you are using an old verison of rust. 
Which version of rust are you using?  
`tantivy 0.5.2` requires a fairly recent version of nightly rust.

If you are uncomfortable with using nightly rust, 0.6 will be released this week and it will work with the imminent stable Rust 1.27

**Comment by yanns** [comment]
I used the last nightly version.
`nightly-x86_64-apple-darwin updated - rustc 1.28.0-nightly (f28c7aef7 2018-06-19)`

```
cargo +nightly run
   Compiling libc v0.2.42
[...]
   Compiling serde_json v1.0.21
error[E0432]: unresolved import `std::collections::range`
  --> /Users/yannsimon/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.5.2/src/query/range_query.rs:11:23
   |
11 | use std::collections::range::RangeArgument;
   |                       ^^^^^ Could not find `range` in `collections`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `tantivy`.

To learn more, run the command again with --verbose.
```

**Comment by fulmicoton** [comment]
Oh right! The range package apparently got deprecated recently.
I am afraid you will have to wait for `0.6.0` later this week.

**Comment by yanns** [comment]
OK thanks for quick feedback!!

**Comment by fulmicoton** [comment]
@yanns. Tantivy 0.6.0 is released.

**Comment by yanns** [comment]
Thx it's working. ❤️
